# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
